version: '3'

services:
  mongo:
    container_name: finance_api
    image: mongo:4.4-focal
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
volumes: 
  data: