module.exports = {
  collectCoverageFrom: [
    '<rootDir>/**/*.ts',
    '**/tests/**',
    '<rootDir>/src/**/*.spec.ts',
    '<rootDir>/**/*.spec.ts',
    '<rootDir>/src/**/*.test.ts',
    '!<rootDir>/src/**/*index.ts',
    '!<rootDir>/src/**/*app.module.ts',
    '!<rootDir>/src/**/*main.ts',
    '!<rootDir>/src/**/*Result.ts',
    '!<rootDir>/src/**/*interface.ts',
    '!<rootDir>/src/**/*env.ts',
    '!<rootDir>/src/Shared/*',
    '!<rootDir>/src/Shared/events/*',
  ],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['\\\\node_modules\\\\'],
  coverageProvider: 'v8',
  roots: ['<rootDir>/'],
  testEnvironment: 'node',
  testPathIgnorePatterns: ['\\\\node_modules\\\\'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  testRegex: '.*\\.spec\\.ts$',
  moduleFileExtensions: ['js', 'json', 'ts'],
};
